name: Roadside Films
favicon: null
layout_spectrum: 0.9420992801897228
typography_spectrum: 0.11707977973856032
title: Roadside Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#757a80'
    - '#4a4f62'
    - '#2b2219'
    - '#9d7f59'
    - '#876945'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
